### ISSUE TITLE
Project Local setup issue while migrating

### ISSUE THREAD

**Issue by sree-hari-s** [nfoert/circles#20]
#6 Issue not yet resolved

**Comment by nfoert** [comment]
Have you deleted the entire Circles folder and started over? Don't forget to pull the most recent changes into your fork as well.

**Comment by sree-hari-s** [comment]
> Have you deleted the entire Circles folder and started over? Don't forget to pull the most recent changes into your fork as well.

Yeah I just tried to start over again and the issue again came.

**Comment by nfoert** [comment]
Hi, thanks for bringing this up again. I think I fixed it now. The issue was caused by [this](https://github.com/nfoert/circles/blob/53f49abde1f0f9899fb1f6d80eb83a0b1b03f370/circles/main/apps.py) adjustment I made. I resolved the issue in the latest commit, and you should be good to go now, the set up worked perfectly for me just now.

**Comment by sree-hari-s** [comment]
this issue is now resolved
