### ISSUE TITLE
[Bug] Error during user creation using admin panel 

### ISSUE THREAD

**Issue by sree-hari-s** [nfoert/circles#24]
**Describe the bug**
User creation in admin panel causing error

**To Reproduce**
![image](https://github.com/nfoert/circles/assets/48482060/8e53f74e-5601-4a55-b74f-e90a7de89294)
![image](https://github.com/nfoert/circles/assets/48482060/51405d56-9f96-493c-9a90-3380cda8a81c)
![image](https://github.com/nfoert/circles/assets/48482060/5f0b674d-c305-4f4d-88d5-8b498bbdf262)

**Expected behavior**
Error message on the admin panel itself.

**Comment by nfoert** [comment]
It's probably not a good idea to create a user account in the admin panel since passwords won't be hashed. (You won't be able to log in since the server is checking for hashed passwords anyway)

This is probably a feature that we need to add though. I wonder if modifying the `save` or `clean` function in the `authentication/models.py` User class could force the password to be hashed.

I don't know exactly why your specific error is happening, though. More investigation is needed, thanks for reporting.

**Comment by nfoert** [comment]
I resolved the error. Switching to using `AbstractBaseUser` requires an attribute so that the model knows what field is the unique identifier for the User.

Thanks for reporting this. I'll create a separate issue for the password hashing.

**Comment by sree-hari-s** [comment]
> I resolved the error. Switching to using `AbstractBaseUser` requires an attribute so that the model knows what field is the unique identifier for the User.
> 
> Thanks for reporting this. I'll create a separate issue for the password hashing.

Yes the password was also an issue that needs to fixed.
